version: '2'
services:
  mongolab:
    image: mongo
  web:
    build: .
    command: 'gulp serve'
    volumes:
        - ./:/app/user
    working_dir: /app/user
    environment:
      PORT: 3000
      MONGODB_URI: 'mongodb://mongolab:27017'
      APP_SECRET: 'very secret key!'
      ORIGINS_WHITELIST: 'http://localhost:3001,http://localhost:8080'
    ports:
      - "3000:3000"